server:
  port: 83
spring:
  application:
    name: cloudalibaba-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#自己的配置
service-url:
  user-service: http://cloudalibaba-provider-payment